[package]
name = "romv"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
description = "Rename Japanese filenames to romaji"

[dependencies]
kakasi = "0.1"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
colored = "2"

[dev-dependencies]
tempfile = "3"
